name: Publish SDK Module manual

on:
  workflow_dispatch:
      inputs:
        module:
          description: 'select publish module'
          required: true
          default: 'autotracker-bom'
          type: choice
          options:
            - autotracker-bom
            - growingio-hybrid
            - growingio-ads
            - growingio-abtest
            - growingio-apm
            - growingio-flutter
            - growingio-compose
            - growingio-data:protobuf
            - growingio-data:json
            - growingio-data:encoder
            - growingio-webservice:circler
            - growingio-webservice:debugger
            - growingio-tools:platform
            - growingio-tools:oaid
            - gio-sdk:tracker
            - gio-sdk:tracker-cdp
            - gio-sdk:autotracker
            - gio-sdk:autotracker-cdp
            - gio-sdk:autotracker-saas
        version:
          description: 'input publish version'
          required: false
          default: 'DEFAULT'
          type: string


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # Gradle 缓存配置
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # 给 gradlew 文件授权
      - name: Grant Permission to Execute
        run: |
          chmod +x gradlew
          chmod +x gradle/publishAllToMavenLocal.sh

      # 构建项目
      - name: Build with Gradle
        run: |
          bash ./gradle/publishAllToMavenLocal.sh

      # 解码秘钥
      - name: Decode
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
      # $(echo ~/.gradle/secring.gpg)

      - name: Publish to MavenCentral
        run: ./gradlew :${{ inputs.module }}:publishToMavenCentral -PCI_SELECT_VERSION="${{ inputs.version }}" --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}